name: CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Format check
        run: |
          if [ -n "$(go fmt ./...)" ]; then
            echo "Code is not formatted. Run 'go fmt ./...'"
            exit 1
          fi

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -race ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Build
        run: go build -race -ldflags "-extldflags '-static'" -o shove ./cmd/shove

      - name: Build Stats
        run: |
          echo "Binary size:"
          ls -lh shove
          echo -e "\nBinary info:"
          file shove
          echo -e "\nDependencies:"
          ldd shove || echo "No dynamic dependencies (statically linked)"
          echo -e "\nSymbols count:"
          nm shove | wc -l

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: shove
      #     path: shove
      #     retention-days: 7
